apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    project: roboshop1
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        # soft limit - minimum resources
        requests:
          memory: "64Mi"
          cpu: 100m
        
        # hard limit - maximum resources
        limits:
          memory: "128Mi"
          cpu: 150m