apiVersion: v1
kind: Pod
metadata:
  name: environmental-variables
  labels: 
    project: roboshop1
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: jenkins_url
          value: https://jenkins_url/com
        - name: docker_url
          value: https://happielearning.com/docker_url4
