apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset
  labels:
    project: roboshop
    purpose: poc
    component: frontend
  annotations:
    kubernetes.io/change-cause: "moving to 1.9"
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      purpose: poc
      component: frontend
  template:
    metadata:
      name: nginx
      labels:
        project: roboshop
        purpose: poc
        component: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.9
